import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/layout/header";
import Footer from "./components/layout/footer";
import BlogProvider from "./context/context";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <BlogProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="bgimg">
            <div className="bg-white/60">
              {/* <Header /> */}
              {children}
              <Footer />
            </div>
          </div>
        </body>
      </html>
    </BlogProvider>
  );
}
